CREATE DATABASE IF NOT EXISTS petclinic;
CREATE USER IF NOT EXISTS 'pc'@'%' IDENTIFIED BY 'pc';
GRANT ALL PRIVILEGES ON petclinic.* TO 'pc'@'%';

USE petclinic;

CREATE TABLE IF NOT EXISTS visits (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  pet_id INT(4) UNSIGNED NOT NULL,
  visit_date DATE,
  description VARCHAR(8192),
  FOREIGN KEY (pet_id) REFERENCES pets(id)
) engine=InnoDB;
