---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: genai-service
  name: genai-service
  namespace: spring-petclinic
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app: genai-service
  type: ClusterIP