---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: billing-service
  name: billing-service
  namespace: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        app: billing-service
    spec:
      containers:
      - image: ${REPOSITORY_PREFIX}/spring-petclinic-billing-service:latest
        name: billing-service
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
          initialDelaySeconds: 90
          periodSeconds: 5
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
          initialDelaySeconds: 15
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 1000m
            memory: 1Gi
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
             secretKeyRef:
               name: billing-db-mysql
               key: mysql-root-password
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: petclinic-config
      restartPolicy: Always