CREATE TABLE IF NOT EXISTS bills (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INT,
    customer_name VARCHAR(100),
    visit_id INT,
    visit_date DATE,
    amount DOUBLE,
    description VARCHAR(255),
    issue_date DATE,
    status VARCHAR(30)
);
